//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshop.Models.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class Carts
    {
        [Key]
        public int CartId { get; set; }
        public int ProductId { get; set; }
        public int CusId { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
    
        public  Customers Customers { get; set; }
        public  Products Products { get; set; }
    }
}
