//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshop.Models.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shopEntities : DbContext
    {
        public shopEntities()
            : base("name=shopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Customers>()
               .HasMany(e => e.Carts)
               .WithRequired(e => e.Customers)
               .WillCascadeOnDelete(false);
            modelBuilder.Entity<Products>()
               .HasMany(e => e.Carts)
               .WithRequired(e => e.Products)
               .WillCascadeOnDelete(false);
            modelBuilder.Entity<Customers>()
               .HasMany(e => e.OrderPlaces)
               .WithRequired(e => e.Customer)
               .WillCascadeOnDelete(false);
        }
    
        public  DbSet<Carts> Carts { get; set; }
        public  DbSet<Customers> Customers { get; set; }
        public  DbSet<OrderPlaces> OrderPlaces { get; set; }
        public  DbSet<Products> Products { get; set; }
    }
}
